apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas:  3
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: lgpepino/generic-images:my-python-app-latest
        imagePullPolicy: Always
        resources:
          limits:
             cpu: 50m
             memory: 100Mi
          requests:
             cpu: 25m
             memory: 10Mi
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001