apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas:  3
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: lgpepino/generic-images:my-python-app-latest
        imagePullPolicy: Always
        resources:
          limits:
             cpu: 50m
             memory: 100Mi
          requests:
             cpu: 25m
             memory: 10Mi
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app
spec:
  ingressClassName: nginx
  rules: 
  - host: python-app-status.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-app
            port:
              number: 5001