apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules: 
  - host: python-app-status.com
    http:
      paths:
      - path: /status
        pathType: Prefix
        backend:
          service:
            name: python-app
            port:
              number: 5001