name: Python APP workflow

on:
    push:
        branches: [ main, develop ]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build the python application

        steps:
            - 
                uses: actions/checkout@v4.1.7
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3.3.0
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}    
            - 
              name: Build and push
              uses: docker/build-push-action@v6.7.0
              with: 
                    context: .
                    push: true
                    #The below line will be used when HELM releases is in place to deploy the images with the tag of the commit SHA
                    #tags: lgpepino/generic-images:my-python-app-${{ github.sha }}
                    tags: lgpepino/generic-images:my-python-app-latest
                    file: ./Dockerfile
    deploy:
        needs: build 
        runs-on: ubuntu-latest
        name: Deploy the application to Cloud Minikube

        steps:
            - 
                uses: actions/checkout@v4.1.7
            - 
                name: Start minikube
                uses: medyagh/setup-minikube@latest
            - 
                name: Try the cluster!
                run: kubectl get pods -A
            - 
                name: Deploy to minikube
                run: 
                    kubectl create namespace dev &&
                    kubectl apply -f kubernetes-manifests/python-app.yaml --namespace dev &&
                    kubectl wait --for=condition=ready pod -l app=python-app --namespace dev
            - 
                name: Test service URLs
                run: |
                    minikube service list
                    minikube service python-app --url --namespace dev
            -
                name: Check if application is running
                run: |
                    check=$(kubectl get pods --namespace dev | awk '{ print $3 }' | grep -i Running | wc -l)
                    if [[ "$check" -eq 3 ]]; then echo "APP is healty"; else exit 1; fi